import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

interface IProduct {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
}

interface CartItem {
  id: number;
  title: string;
  price: number;
  image: string;
}
const Home: NextPage<IProduct[]> = ({ products }: { products: IProduct[] }) => {
  
  const handleAddToCart = (product) => {
    let cartItems: CartItem[] =
      JSON.parse(localStorage.getItem('cart-items')) || [];

    const oldIndex = cartItems.findIndex((item) => item.id === product.id);

    if (oldIndex > -1) {
      cartItems[oldIndex] = {
        ...cartItems[oldIndex],
        quantity: cartItems[oldIndex].quantity + 1,
      };
      localStorage.setItem('cart-items', JSON.stringify(cartItems));
    } else {
      const newItem = {
        id: product.id,
        title: product.title,
        price: product.price,
        quantity: 1,
      };
      cartItems = [...cartItems, newItem];
      localStorage.setItem('cart-items', JSON.stringify(cartItems));
    }
  };
  return (
    <div className="p-4">
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-semibold mb-5">All Products</h1>
      <section className="grid gap-7 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 w-full">
        {products.map((product) => {
          return (
            <Link href="/" key={product.id}>
              <article className="p-4 border shadow-md bg-white rounded-md  flex flex-col justify-between space-y-1">
                <img
                  src={product.image}
                  className="w-full object-contain h-[200px]"
                  height={100}
                />
                <h1 className="text-blue-600 text-md capitalize mb-1 font-normal">
                  {product.title}
                </h1>
                <p>{product.description.slice(0, 100)}...</p>
                <p className="text-lg font-semibold">${product.price}</p>
                <button
                  className="bg-blue-600 rounded-md shadow text-white font-semibold p-2 w-full cursor-pointer"
                  onClick={() => handleAddToCart(product)}
                >
                  Add to cart
                </button>
              </article>
            </Link>
          );
        })}
      </section>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch('https://fakestoreapi.com/products/');
  const products = await res.json();

  return {
    props: { products },
  };
}

export default Home;

const data = [
  {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 109.95,
    description:
      'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 3.9, count: 120 },
  },
];
